name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
  
    - name: Build x64 Win app
      run: dotnet publish .\WindowsWithPrompt\dotnet-version-check-win.csproj -c Release -r win7-x64

    - name: Build x86 Win app
      run: dotnet publish .\WindowsWithPrompt\dotnet-version-check-win.csproj -c Release -r win7-x86

    - name: Build x64 console app
      run: dotnet publish .\Console\dotnet-version-check-console.csproj -c Release -r win7-x64

    - name: Build x86 console app
      run: dotnet publish .\Console\dotnet-version-check-console.csproj -c Release -r win7-x86
